name: batch_inference
root: ~/sim_ws

windows:
  - learning_e2e:
      layout: tiled
      panes:
        - shell:
        - core:
          - roscore
        - bridge:
          - roslaunch --wait social_sim_ros sim_tcp_bridge.launch
        - move_base:
          - roslaunch --wait social_sim_ros kuri_move_base_global_only.launch
        - description:
          - roslaunch --wait social_sim_ros kuri_description.launch
        - map_publisher:
          - rosrun social_sim_ros map_publisher.py
        - controller:
          - roslaunch --wait lifecycle_learning e2e_controller.launch experiment:=<%=@settings['experiment']%> npzpath:=<%=@settings['extracted-path']%> situationsource:=<%=@settings['situation-source']%> situationtomodel:=<%=@settings['situation-model']%>
        - rviz:
          - rosrun rviz rviz -d $(rospack find social_sim_ros)/config/move.rviz
        - scan:
          - roslaunch --wait social_sim_ros depth_to_laserscan.launch
        - recorder:
          - rosrun social_sim_ros ros_controlled_recorder.py prefix:=/media/alec/